// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AskAI(arg1:models.AIAskRequest):Promise<void>;

export function CancelAIRequest(arg1:string):Promise<void>;

export function ClearAIAPIKey():Promise<void>;

export function ConvertFileContent(arg1:string):Promise<string>;

export function ConvertToMarkdown(arg1:string):Promise<models.Item>;

export function CreateExamDate(arg1:string,arg2:string):Promise<models.ExamDate>;

export function CreateFolder(arg1:string,arg2:string):Promise<models.Item>;

export function CreateMarkdownFile(arg1:string,arg2:string,arg3:string):Promise<models.Item>;

export function CreatePassedExam(arg1:string,arg2:number,arg3:boolean,arg4:number,arg5:string):Promise<models.PassedExam>;

export function CreateWebLink(arg1:string,arg2:string,arg3:string):Promise<models.Item>;

export function DeleteExamDate(arg1:string):Promise<void>;

export function DeleteItem(arg1:string,arg2:boolean):Promise<void>;

export function DeletePassedExam(arg1:string):Promise<void>;

export function DeletePodcast(arg1:string):Promise<void>;

export function DeleteStudyHandout(arg1:string):Promise<void>;

export function EmptyTrash():Promise<void>;

export function ExportFile(arg1:string):Promise<void>;

export function GetAllFolders():Promise<Array<models.Item>>;

export function ExportPodcastAudio(arg1:string):Promise<void>;

export function ExportPodcastScript(arg1:string):Promise<void>;

export function ExportStudyHandoutMarkdown(arg1:string):Promise<void>;

export function GeneratePodcast(arg1:models.PodcastGenerateRequest):Promise<models.PodcastEpisode>;

export function GenerateStudyHandout(arg1:models.StudyHandoutGenerateRequest):Promise<models.StudyHandout>;

export function GetAISettings():Promise<models.AISettings>;

export function GetAppStoragePath():Promise<string>;

export function GetBreadcrumbs(arg1:string):Promise<Array<models.Breadcrumb>>;

export function GetFileBase64(arg1:string):Promise<string>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFileUrl(arg1:string):Promise<string>;

export function GetPodcast(arg1:string):Promise<models.PodcastEpisode>;

export function GetPodcastAudioBase64(arg1:string):Promise<string>;

export function GetStorageStats():Promise<models.StorageStats>;

export function GetStudyHandout(arg1:string):Promise<models.StudyHandout>;

export function ImportAndConvertToMarkdown(arg1:string):Promise<Array<models.Item>>;

export function ImportFileByPath(arg1:string,arg2:string):Promise<models.Item>;

export function ImportFiles(arg1:string):Promise<Array<models.Item>>;

export function ListAIModels(arg1:string):Promise<Array<models.AIModelInfo>>;

export function ListExamDates():Promise<Array<models.ExamDate>>;

export function ListItems(arg1:string,arg2:string):Promise<Array<models.Item>>;

export function ListPassedExams():Promise<Array<models.PassedExam>>;

export function MoveItem(arg1:string,arg2:string):Promise<void>;

export function ListPodcasts():Promise<Array<models.PodcastEpisode>>;

export function ListStudyHandouts():Promise<Array<models.StudyHandout>>;

export function OpenFileLocally(arg1:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function RestoreItem(arg1:string):Promise<void>;

export function SaveAISettings(arg1:string,arg2:string):Promise<void>;

export function SaveFileFromBase64(arg1:string,arg2:string,arg3:string):Promise<models.Item>;

export function SaveMarkdownFile(arg1:string,arg2:string):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SaveStudyHandoutToDrive(arg1:string,arg2:string):Promise<models.Item>;

export function SearchItems(arg1:string):Promise<Array<models.Item>>;

export function UpdatePassedExam(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:number,arg6:string):Promise<models.PassedExam>;

export function UpdateStudyHandout(arg1:string,arg2:string,arg3:string):Promise<void>;
