// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateExamDate(arg1, arg2) {
  return window['go']['main']['App']['CreateExamDate'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateWebLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWebLink'](arg1, arg2, arg3);
}

export function DeleteExamDate(arg1) {
  return window['go']['main']['App']['DeleteExamDate'](arg1);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['main']['App']['DeleteItem'](arg1, arg2);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function ExportFile(arg1) {
  return window['go']['main']['App']['ExportFile'](arg1);
}

export function GetAppStoragePath() {
  return window['go']['main']['App']['GetAppStoragePath']();
}

export function GetBreadcrumbs(arg1) {
  return window['go']['main']['App']['GetBreadcrumbs'](arg1);
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function ImportFileByPath(arg1, arg2) {
  return window['go']['main']['App']['ImportFileByPath'](arg1, arg2);
}

export function ImportFiles(arg1) {
  return window['go']['main']['App']['ImportFiles'](arg1);
}

export function ListExamDates() {
  return window['go']['main']['App']['ListExamDates']();
}

export function ListItems(arg1, arg2) {
  return window['go']['main']['App']['ListItems'](arg1, arg2);
}

export function OpenFileLocally(arg1) {
  return window['go']['main']['App']['OpenFileLocally'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2);
}

export function RestoreItem(arg1) {
  return window['go']['main']['App']['RestoreItem'](arg1);
}

export function SaveFileFromBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileFromBase64'](arg1, arg2, arg3);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}
