// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function CancelAIRequest(arg1) {
  return window['go']['main']['App']['CancelAIRequest'](arg1);
}

export function ClearAIAPIKey() {
  return window['go']['main']['App']['ClearAIAPIKey']();
}

export function ConvertFileContent(arg1) {
  return window['go']['main']['App']['ConvertFileContent'](arg1);
}

export function ConvertToMarkdown(arg1) {
  return window['go']['main']['App']['ConvertToMarkdown'](arg1);
}

export function CreateExamDate(arg1, arg2) {
  return window['go']['main']['App']['CreateExamDate'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateMarkdownFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMarkdownFile'](arg1, arg2, arg3);
}

export function CreatePassedExam(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreatePassedExam'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateWebLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWebLink'](arg1, arg2, arg3);
}

export function DeleteExamDate(arg1) {
  return window['go']['main']['App']['DeleteExamDate'](arg1);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['main']['App']['DeleteItem'](arg1, arg2);
}

export function DeletePassedExam(arg1) {
  return window['go']['main']['App']['DeletePassedExam'](arg1);
}

export function DeletePodcast(arg1) {
  return window['go']['main']['App']['DeletePodcast'](arg1);
}

export function DeleteStudyHandout(arg1) {
  return window['go']['main']['App']['DeleteStudyHandout'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function ExportFile(arg1) {
  return window['go']['main']['App']['ExportFile'](arg1);
}

export function GetAllFolders() {
  return window['go']['main']['App']['GetAllFolders']();
}

export function ExportPodcastAudio(arg1) {
  return window['go']['main']['App']['ExportPodcastAudio'](arg1);
}

export function ExportPodcastScript(arg1) {
  return window['go']['main']['App']['ExportPodcastScript'](arg1);
}

export function ExportStudyHandoutMarkdown(arg1) {
  return window['go']['main']['App']['ExportStudyHandoutMarkdown'](arg1);
}

export function GeneratePodcast(arg1) {
  return window['go']['main']['App']['GeneratePodcast'](arg1);
}

export function GenerateStudyHandout(arg1) {
  return window['go']['main']['App']['GenerateStudyHandout'](arg1);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetAppStoragePath() {
  return window['go']['main']['App']['GetAppStoragePath']();
}

export function GetBreadcrumbs(arg1) {
  return window['go']['main']['App']['GetBreadcrumbs'](arg1);
}

export function GetFileBase64(arg1) {
  return window['go']['main']['App']['GetFileBase64'](arg1);
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFileUrl(arg1) {
  return window['go']['main']['App']['GetFileUrl'](arg1);
}

export function GetPodcast(arg1) {
  return window['go']['main']['App']['GetPodcast'](arg1);
}

export function GetPodcastAudioBase64(arg1) {
  return window['go']['main']['App']['GetPodcastAudioBase64'](arg1);
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function GetStudyHandout(arg1) {
  return window['go']['main']['App']['GetStudyHandout'](arg1);
}

export function ImportAndConvertToMarkdown(arg1) {
  return window['go']['main']['App']['ImportAndConvertToMarkdown'](arg1);
}

export function ImportFileByPath(arg1, arg2) {
  return window['go']['main']['App']['ImportFileByPath'](arg1, arg2);
}

export function ImportFiles(arg1) {
  return window['go']['main']['App']['ImportFiles'](arg1);
}

export function ListAIModels(arg1) {
  return window['go']['main']['App']['ListAIModels'](arg1);
}

export function ListExamDates() {
  return window['go']['main']['App']['ListExamDates']();
}

export function ListItems(arg1, arg2) {
  return window['go']['main']['App']['ListItems'](arg1, arg2);
}

export function ListPassedExams() {
  return window['go']['main']['App']['ListPassedExams']();
}

export function MoveItem(arg1, arg2) {
  return window['go']['main']['App']['MoveItem'](arg1, arg2);
}

export function ListPodcasts() {
  return window['go']['main']['App']['ListPodcasts']();
}

export function ListStudyHandouts() {
  return window['go']['main']['App']['ListStudyHandouts']();
}

export function OpenFileLocally(arg1) {
  return window['go']['main']['App']['OpenFileLocally'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2);
}

export function RestoreItem(arg1) {
  return window['go']['main']['App']['RestoreItem'](arg1);
}

export function SaveAISettings(arg1, arg2) {
  return window['go']['main']['App']['SaveAISettings'](arg1, arg2);
}

export function SaveFileFromBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileFromBase64'](arg1, arg2, arg3);
}

export function SaveMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['SaveMarkdownFile'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SaveStudyHandoutToDrive(arg1, arg2) {
  return window['go']['main']['App']['SaveStudyHandoutToDrive'](arg1, arg2);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function UpdatePassedExam(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdatePassedExam'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateStudyHandout(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStudyHandout'](arg1, arg2, arg3);
}
