// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateFolder(arg1:string,arg2:string):Promise<models.Item>;

export function DeleteItem(arg1:string,arg2:boolean):Promise<void>;

export function EmptyTrash():Promise<void>;

export function ExportFile(arg1:string):Promise<void>;

export function GetAppStoragePath():Promise<string>;

export function GetBreadcrumbs(arg1:string):Promise<Array<models.Breadcrumb>>;

export function GetStorageStats():Promise<models.StorageStats>;

export function ImportFileByPath(arg1:string,arg2:string):Promise<models.Item>;

export function ImportFiles(arg1:string):Promise<Array<models.Item>>;

export function ListItems(arg1:string,arg2:string):Promise<Array<models.Item>>;

export function OpenFileLocally(arg1:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function RestoreItem(arg1:string):Promise<void>;

export function SaveFileFromBase64(arg1:string,arg2:string,arg3:string):Promise<models.Item>;

export function SearchItems(arg1:string):Promise<Array<models.Item>>;
